config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
    get 'zip_code', to: 'zip_code#show'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    # resources :admins, except: [:destroy] --- ficou como exemplo de exclusão
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :users
  devise_for :admins, skip: [:registrations]

  get 'inicio', to: 'site/welcome#index'
  get 'admin', to: 'admins_backoffice/welcome#index'

  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  searchkick

  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  # callback
  after_create :set_statistic

  # kaminari
  paginates_per 5

  scope :_search_, ->(page, term) {
    includes(:answers, :subject)
    .where("lower(description) LIKE ?", "%#{term.downcase}%")
    .page(page)
  }

  scope :_search_subject_, ->(page, subject_id) {
    includes(:answers, :subject)
    .where(subject_id: subject_id)
    .page(page)
  }

  private

  def set_statistic
    AdminStatistic.set_event(AdminStatistic::EVENTS[:total_questions])
  end
   
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    # esse é o padrão sem paginação
    # @admins = Admin.all

    # com paginação com a gema kaminari
    @admins = Admin.all.page(params[:page]).per(5)
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Novo administrador inserido"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado"
    else
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluído"
    else
      render :index
    end
  end

  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin
    @admin = Admin.find(params[:id])
  end

  # se a senha não for preechida, retira os campos de 
  # senha da hash para poder salvar o resto sem dar erro de senha em branco
  def verify_password
    if params[:admin][:password].blank? &&params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:edit, :new]

  def index
    @questions = Question.includes(:subject).all.order(:id).page(params[:page])
  end

  def new
   @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

  private

  def params_question
    params.require(:question)
          .permit(:description, 
                  :subject_id,
                  answers_attributes: [:id, :description, :correct, :_destroy]) # essa linha é referente ao Nested Attributes, realizado com cooperação da gema Cocoon
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html {@subjects = Subject.all.order(:description).page(params[:page]).per(25)}
      format.pdf {@subjects = Subject.all.order(:description)}
      #format.json { render json: (@subjects = Subject.all.order(:description)), except: [:created_at, :updated_at, :questions_count]}
      format.json { @subjects = Subject.all.order(:description) }
    end
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: "Novo assunto inserido"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: "Assunto atualizado"
    else
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto excluído"
    else
      render :index
    end
  end

  private

  def params_subject
    params.require(:subject).permit(:description)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @total_questions = AdminStatistic.total_questions
    @total_users = AdminStatistic.total_users
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    layout 'admins_backoffice'
    before_action :authenticate_admin!
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    if (object && method)
      object.model.human_attribute_name(method)
    else
      'Informe corretamente os parâmetros'
    end
  end
end

app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested-fields">
  <%= f.label :description %><br>
  <%= f.text_field :description %>
  <%= f.check_box :correct %> Correta?
  <%= link_to_remove_association('remover', f) %>
</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
            locals: { action_message: 'Edição de' } %>

app/views/admins_backoffice/questions/index.html.erb
<h1><%= t('messages.listing', model: @questions.model_name.human(count: 2)) %></h1>

<table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
  <thead>
      <tr role="row">
        <th class="sorting_asc" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending">#</th>
        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" ><%= translate_attribute(@questions, :subject) %></th>
        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" ><%= translate_attribute(@questions, :description) %></th>
        <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" >
          <%= link_to new_admins_backoffice_question_path, class:"btn btn-success btn-circle btn-sm" do %>
            <i class="fas fa-plus"></i>
          <% end %>        
        </th>
      </tr>
  </thead>
  <tbody> 
    <%@questions.each do |question| %>                                       
      <tr role="row" class="odd">
        <td><%= question.id %></td>
        <td><%= question.subject.description %></td>
        <td><%= sanitize question.description.truncate(50) %></td>
        <td>
          <%= link_to edit_admins_backoffice_question_path(question.id), class:"btn btn-info btn-circle btn-sm" do %>
            <i class="fas fa-edit"></i>
          <% end %>
          <%= link_to admins_backoffice_question_path(question.id), method: :delete, class:"btn btn-danger btn-circle btn-sm", data: {confirm: t('messages.confirm_with', item: question.description.truncate(15))} do %>
            <i class="fas fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
</table>
<%= paginate@questions %>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
            locals: { action_message: 'Nova' } %>